name: Deploy the galpy.org/repl redirect

on:
  push:
    branches:
      - main
    paths:
      - 'repl'
      - 'prerun.py'
      - '.github/workflows/deploy-repl-redirect.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'repl'
      - 'prerun.py'
      - '.github/workflows/deploy-repl-redirect.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Add prerun.py code
        run: |
          CODE_FROM_PRERUN_DOT_PY=$(python -c "import urllib.parse; f= open('prerun.py','r'); out= [urllib.parse.quote(line,safe='')+'%0A' for line in f.readlines() if line[0] != '#']; f.close(); print(''.join(out))")
          sed -i 's/CODE_FROM_PRERUN_DOT_PY/'"$CODE_FROM_PRERUN_DOT_PY"'/g' repl
      - name: Upload repl re-direct
        uses: jobovy/s3-upload-github-action@master
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          args: --acl public-read --content-type text/html
        env:
          FILE: repl
          S3_KEY: repl
          AWS_REGION: 'us-east-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}