name: Deploy the galpy.org/repl redirect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload repl re-direct
        uses: jobovy/s3-upload-github-action@master
        with:
          args: --acl public-read --content-type text/html
        env:
          FILE: repl
          S3_KEY: repl
          AWS_REGION: 'us-east-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}