name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'repl'
      - 'prerun.py'
      - '.github/workflows/deploy-repl-redirect.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'repl'
      - 'prerun.py'
      - '.github/workflows/deploy-repl-redirect.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          # When updating this, also update jupyterlite-core and -pyodide-kernel versions 
          # below and the galpy version in the prerun.py file
          python-version: "3.12"
      - name: Install JupyterLite
        run: python -m pip install jupyterlite-core==0.6.4
      - name: Install pyodide-kernel extension
        run: python -m pip install jupyterlite-pyodide-kernel==0.6.1
      - name: Install my jupyterlite_repl_prerun extension
        run: python -m pip install jupyterlite_repl_prerun
# and let's create an empty site
      - name: create output dir
        run: mkdir output
      - name: Build jupyterlite REPL
        working-directory: output
        run: jupyter lite build --apps repl --no-unused-shared-packages --no-sourcemaps
# Edit the jupyter-lite.json to use galpy's favicon
      - name: Edit jupyter-lite.json config
        working-directory: output/_output
        run: python -c "import json; jsonFile = open('jupyter-lite.json'); data= json.load(jsonFile); jsonFile.close(); data['jupyter-config-data']['faviconUrl']= '../../images/logo-small.ico'; jsonFile= open('jupyter-lite.json','w'); json.dump(data,jsonFile,indent=2); jsonFile.close()"
# Touch all files so they sync to S3
      - name: Touch files
        working-directory: output/_output
        run: find . -type f -exec touch {} +
# Create artifact for debugging        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Test-${{ github.run_number }}
          path: ./output/_output
# Push to Amazon S3
      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: './output/_output'
          DEST_DIR: 'repl'